### PR TITLE
WIP: Add Elasticsearch support

### PR DESCRIPTION
**Pull request by dkarlovi**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/rollerworks/search/issues/179
| License       | MIT
| Doc PR        | (pending)

https://github.com/rollerworks/search/issues/179

### CODE REVIEW

**Comment by dkarlovi** [comment]
OK, so the first question here is: how do we actually do a query to Elasticsearch? Obvious choice seems FOS Elastica Bundle, I can inject their client and use it from there.

A more clean solution would be to add our own interface and then decorate their service with it, but keeping an option to inject other solutions.

WDYT @sstok?

**Comment by dkarlovi** [comment]
Same question as with https://github.com/rollerworks/search-api-platform/pull/8:

> @sstok So what do you think about this as it is? What changes would you like to see to get this merged?

**Comment by dkarlovi** [comment]
Build is failing because there's no Elasticsearch stuff in current API Platform repo. :) That's why you want mono-repo. \o/

**Comment by sstok** [comment]
Can you reopen this against https://github.com/rollerworks/search 👍

**Pull request closed without merging**
